# Generated by Django 2.0.2 on 2021-01-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmPostEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_code', models.CharField(max_length=60)),
                ('aiserving_version', models.CharField(max_length=60)),
                ('post_num', models.PositiveIntegerField()),
            ],
        ),
    ]
